config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'breaks/edit'
  get 'users/index'
  get 'works/index'
  get 'works/create'
  #root to: "works#chart"
  root to: "works#new"
  get 'works/break'
  get 'works/drink'
  get 'works/bgm'
  get 'works/evaluation'
  get 'works/edit'
  get 'works/works_end'
  post 'works/create'
  post 'works/update'
  post 'breaks/create'
  post 'breaks/update'
  get 'break/new'
  patch 'breaks/:id' , to: 'breaks#update'
  patch 'works/:id' , to: 'works#update'
  resources :works do
    resources :breaks
  end
    resources :breaks, only: [:new , :create ,:index,:edit,:update]
    resources :works, only: [:new , :create ,:index,:edit,:update]do
    member do
      get 'work_end'
    end
  end

 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/break.rb
class Break < ApplicationRecord
  belongs_to :work
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         validates :nickname, presence: true
         PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+{6,}\z/i.freeze
         validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字を含めて設定してください'
         validates :sex, presence: true
         validates :age, presence: true

         has_many :breaks
         end

app/models/work.rb
class Work < ApplicationRecord
has_many :breaks
belongs_to :user

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname,:email,:encrypted_password,:sex,:age ])
  end
  private
  def basic_auth
   authenticate_or_request_with_http_basic do |username, password|
     username == 'admin' && password == '2222'
   end
 end
end

app/controllers/breaks_controller.rb
class BreaksController < ApplicationController
  before_action :set_break, only: [:create]
  def new
    #@work = Work.find(params[:work_id])
    #@break = Break.new(break_params)
   # @break_start_time = Time.zone.now.to_i
  end
  def create
    @work = Work.find(params[:work_id])
    @break = Break.new(break_params)
    if @break.save
      redirect_to controller: :breaks, action: :edit, id: @break.id,work_id:@work.id
    else 
      redirect_to controller: :works, action: :new
    end
  end
  def edit
    @work = Work.find(params[:work_id])
    @break = Break.find(params[:id])
  end

  def update

    @work = Work.find(params[:work_id])
    @break = Break.find(params[:id])
    if @break.update(break_params )
      @work = Work.find(params[:work_id])
      redirect_to controller: :works, action: :edit ,id:params[:work_id]
      #render "works/edit" ,{id: params[:work_id]}
    end
  end

def set_break
  @break = Break.new
end
  private

  def break_params
    params.permit(:created_at,:updated_at,:breakcount).merge(work_id: params[:work_id].to_i)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :authenticate_user!, except: [:new]

  def new
    Groupdate.time_zone = "Tokyo"
    @array = Array.new()
    @work = Work.new
    if  user_signed_in?
    gon.work_time_along = Work.where(user_id: current_user.id).pluck(:work_time).last(4)
    gon.work_break_along = Work.where(user_id: current_user.id).pluck(:break_time).last(4)
    gon.work_evaluation = Work.where(user_id: current_user.id).pluck(:evaluation).last(4)
    end
  end
  def create
    @work = Work.new(work_params)
    if @work.save
      redirect_to controller: :works,action: :edit, id: @work.id
    end
 
    
   # @work_time = (Time.now-@start_time)
  end
  def break
    #binding.pry
  end
  def edit
    @work = Work.find(params[:id])
  end
  def evaluation
    @work = Work.find(params[:id])

  end

  def update
    @work = Work.find(params[:id])
    #if @work.update(work_params)

   if @work.update(work_params)
     redirect_to action: :work_end 
    else
      render 'works/evaluation'

   end
   def work_end
    #binding.pry
    @work = Work.find(params[:id])
    @start_time = @work.created_at.to_f
    @end_time = @work.updated_at.to_f


    @arrayend = Break.where(work_id: @work.id).pluck(:updated_at)
    @arraystart = Break.where(work_id: @work.id).pluck(:created_at)
    @array = [@arrayend,@arraystart].transpose.map{|ary| ary.inject(:-)}
    @array = @array.sum
    ti = @end_time - @start_time - @array

     if ti >= 3600
    t = Time.at(ti-9*60*60)
   @t = t.strftime("%H:%M:%S")
   @arrayone = Time.at(@array - 9*60*60)
   @arrayone = @arrayone.strftime("%M:%S")
     else
    t = Time.at(ti-9*60*60)
    @t = t.strftime("%M:%S")
    @arrayone = Time.at(@array - 9*60*60)
    @arrayone = @arrayone.strftime("%M:%S")
     end

     @work.update(work_time: ti.to_f,break_time: @array.to_f)
   end

  end



  private
  def work_params
    params.permit(:created_at,:updated_at,:work_time,:work_id,:evaluation).merge(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/break_helper.rb
module BreakHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/work_helper.rb
module WorkHelper
end

app/views/breaks/edit.html.erb
  <div class='break_top'> 
    <span class='work-break-text'>休憩中</span>
  </div>
  <div class="work-break">
    <%= button_to "作業に戻る",{controller:"breaks",action:"update"},{method: :patch,class: 'work-btn-break',params: {id: params[:work_id],breakcount:1}} %>
    <%#  <div class ='naraberu'>
        <%= link_to(works_drink_path, class: 'drink-btn') do %>
     <%#   <span class='drink-btn-text'>ドリンク</span>
        <%end%>
      <%#  <%= link_to(works_bgm_path, class: 'bgm-btn-break') do %>
      <%#  <span class='bgm-btn-text'>BGM</span>
        <%end%>
      </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sakutomo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <%= include_gon %>
    <script type="text/javascript" src="worktime.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>

    </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/works/bgm.html.erb
<div class='bgm_top'>
<div class="work-break">
   <span class='work-break-text'>BGM</span>
  </div>
    <%= link_to(root_path, class: 'drink-btn') do %>
      <span class='drink-btn-text'>戻る</span>
    <%end%>
</div>

app/views/works/break.html.erb
<div class='break_top'>
<div class="work-break">
   <span class='work-break-text'>休憩中</span>
  </div>
    <%= link_to(works_drink_path, class: 'drink-btn') do %>
      <span class='drink-btn-text'>ドリンク</span>
    <%end%>
    <%= link_to(works_bgm_path, class: 'bgm-btn') do %>
      <span class='bgm-btn-text'>BGM</span>
    <%end%> 
    <%= button_to "作業に戻る",{controller:"works",action:"new"},{method: :get,class: 'work-btn',params:{break_end_time: Time.zone.now.to_i}} %>
     <%#= link_to(works_now_work_path, class: 'work-btn') do %>
      <<%#span class='work-btn-text'>作業に戻る</span>
    <%end%>
</div>

app/views/works/drink.html.erb
<div class='drink-countents'>
  <div class="dorink-calam">
   <span class='drink-page'>ドリンクページ</span>
  </div>
    <%= link_to( works_break_path, class: 'drink-btn') do %>
      <span class='drink-btn-text'>戻る</span>
    <%end%>
</div>

app/views/works/edit.html.erb
  <div class="now-work">
      <span class='now-work-text'>作業中</span>
  </div>
<div class= 'center'>
  <div class='works-new-countents'>
   <div class= 'work_right_second'>
            <div class= 'buttonposi'>
             <%= button_to "ちょっと休憩",{controller:"breaks",action:"create"},{method: :post,class: 'break-btn',params: {work_id: params[:id]}} %>
         <%= button_to "今日の作業を終わる",works_evaluation_path,{method: :get,class: 'end-btn',params: {id: params[:id]}} %>

                 </div>
       </div>
        <div class = 'work_reft_second'>
         <div class = 'reft_center'>

             <%#= link_to(works_bgm_path, class: 'bgm-btn-second') do %>
            <%#  <span class='bgm-btn-text'>BGM</span>
                       
            <%end%>
            </div>
        </div>
   </div>
</div>

app/views/works/evaluation.erb
<div class= 'evaluation_head-eva'>
  <%= form_with model: @works, url: work_path(params[:id]),method: :patch, class: 'registration-main-eva', local: true do |f| %>

  <div class="form-group-eva">
    <div class='form-text-wrap-eva'>
      <label class="form-text-eva">今日の作業評価</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap-eva'>
    <li> <%= f.radio_button :evaluation, 1 %>
     <%= f.label :evaluation, "集中できなかった", {value: :male, style: "display: inline-block;"} %>
   <li>   <%= f.radio_button :evaluation, 2 %>
     <%= f.label :evaluation, "集中できた", {value: :male, style: "display: inline-block;"} %>
   <li>  <%= f.radio_button :evaluation, 3 %>
     <%= f.label :evaluation, "前回以上に集中できた", {value: :male, style: "display: inline-block;"} %>
   <li>  <%= f.radio_button :evaluation, 4 %>
     <%= f.label :evaluation, "最高に集中できた", {value: :male, style: "display: inline-block;"} %>

    </div>
    

  <div class='register-btn' >
    <%= f.submit "完了" ,class:"register-red-btn"%>

<% end %>
</div>

app/views/works/new.html.erb
<div class = 'top'>
    <header class = 'header'>
        <% if user_signed_in? %>
          <div class='header-one'>
          <li>こんにちわ！<%= link_to current_user.nickname, "#", class: "user-nickname"%>さん</li> 
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout-btn" %>
          </div>
        <% else %>
          <div class = 'header-two'>
          <li><%= link_to 'ログイン',  new_user_session_path, class: "session-btn" %></li>
          <li><%= link_to '新規登録', new_user_registration_path, class: "sinin-btn-hed" %></li>
          </div>
        <% end %>
      </div>
    </header>
   <div class='works-new-countents'>
      <div class= 'work_right'>
         <% if params[:start_time] == nil %>
           <%= button_to "作業開始！",{controller:"works",action:"create"},{method: :post,class: 'work-btn',id: "work_start"} %>
         <%end%>
<%#
         <%= link_to 'BGM', works_bgm_path, class: "btn btn--orange btn--cubic btn--shadow" %>
      </div>
      <div class = 'work_reft'>
         <div class = 'chart'>
         <% if user_signed_in? %>
           <canvas id="myLineChart"width="400" height="300"></canvas>
           <%end%>
         </div>
      </div>
   </div>
</div>

app/views/works/work_end.html.erb
<div class = 'works-end-countents'>
   <span class='work-end-text'>お疲れ様でした！</span>
   <div class = 'work_time'>
  <br>今日の作業時間は
  <%=@t%><a>でした</a>
  <br>休憩時間は<%=@arrayone%><a>です！</a>
  <br>また明日もがんばりましょう！
    </div>
          <%= link_to("http://localhost:3000", class: 'root-btn', data: {"turbolinks" => false}) do %>
      <span class='root-btn-text'>ホームに戻る</span>
    <%end%> 

</div>